from .lesson1_1 import print_simple as p1_print_simple
from .lesson1_2 import sec_to_time as p2_sec_to_time
from .lesson1_3 import wild_s as p3_wild_s
from .lesson1_4_1 import greatest_digit as p4_greatest_digit_1
from .lesson1_4_2 import greatest_digit as p4_greatest_digit_2
from .lesson1_4_3 import greatest_digit as p4_greatest_digit_3
from .lesson1_4_4 import greatest_digit as p4_greatest_digit_4
from .lesson1_5 import some_economics as p5_some_economics
from .lesson1_6 import fitness_tracker as p6_fitness_tracker
